services:

  moneybe:
    image: moneybe
    ports:
      - 3000:3000
    restart: always
    networks:
      - app-network

  db: 
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: qwerty1234
      POSTGRES_USER: postgres
      POSTGRES_DB: db123
    networks:
      - app-network


networks:
  app-network:
    external: true


